### PR TITLE
Add Nano support

### PR DESCRIPTION
**Pull request by roosmaa**
This PR adds primitives needed for Nano support.

### CODE REVIEW

**Comment by keepkeyjon** [comment]
This ought to be upstreamed, if SatoshiLabs folks are interested in it.

**Comment by roosmaa** [comment]
Rebased on latest master.

**Comment by roosmaa** [comment]
Also, will be investigating if Trezor is interested in me upstreaming these changes...

**Comment by roosmaa** [comment]
Upstreaming is a [no-go for now](https://github.com/trezor/trezor-common/issues/274#issuecomment-462970721).

**Pull request merged**
